// <auto-generated />
using GT86Registry.Core.Entities;
using GT86Registry.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GT86Registry.Infrastructure.Data.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    partial class VehicleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GT86Registry.Core.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasMaxLength(3);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.ColorsModelYears", b =>
                {
                    b.Property<int>("ColorId");

                    b.Property<int>("ModelYearId");

                    b.HasKey("ColorId", "ModelYearId");

                    b.HasIndex("ModelYearId");

                    b.ToTable("ModelColor");
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Uri");

                    b.HasKey("Id");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ActiveEndDate");

                    b.Property<DateTime>("ActiveStartDate");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("ManufacturerId");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Model");
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.ModelTransmissions", b =>
                {
                    b.Property<int>("ModelYearId");

                    b.Property<int>("TransmissionId");

                    b.HasKey("ModelYearId", "TransmissionId");

                    b.HasIndex("TransmissionId");

                    b.ToTable("ModelTransmission");
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.ModelYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("ModelId");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("ModelYear");
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.Transmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("Name");

                    b.HasKey("Id");

                    b.ToTable("Transmission");
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.Vehicle", b =>
                {
                    b.Property<string>("VIN")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(17);

                    b.Property<int>("ColorId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Facebook_Uri");

                    b.Property<string>("Instagram_Uri");

                    b.Property<int>("ModelYearId");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<int>("ProfilePhotoId");

                    b.Property<int>("TransmissionId");

                    b.Property<string>("UserIdentityGuid");

                    b.Property<int>("VehicleLocationId");

                    b.HasKey("VIN");

                    b.HasIndex("ColorId");

                    b.HasIndex("ModelYearId");

                    b.HasIndex("ProfilePhotoId");

                    b.HasIndex("TransmissionId");

                    b.HasIndex("VehicleLocationId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.VehicleLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<DateTimeOffset>("TimeStamp");

                    b.Property<string>("VehicleVIN");

                    b.HasKey("Id");

                    b.HasIndex("VehicleVIN");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.VehiclesImages", b =>
                {
                    b.Property<int>("VehicleId");

                    b.Property<int>("ImageId");

                    b.Property<string>("VehicleVIN");

                    b.HasKey("VehicleId", "ImageId");

                    b.HasIndex("ImageId");

                    b.HasIndex("VehicleVIN");

                    b.ToTable("VehicleImage");
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.ColorsModelYears", b =>
                {
                    b.HasOne("GT86Registry.Core.Entities.Color", "Color")
                        .WithMany("ModelColors")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GT86Registry.Core.Entities.ModelYear", "ModelYear")
                        .WithMany("ModelColors")
                        .HasForeignKey("ModelYearId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.Model", b =>
                {
                    b.HasOne("GT86Registry.Core.Entities.Manufacturer", "Manufacturer")
                        .WithMany("VehicleModels")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.ModelTransmissions", b =>
                {
                    b.HasOne("GT86Registry.Core.Entities.ModelYear", "ModelYear")
                        .WithMany("ModelTransmissions")
                        .HasForeignKey("ModelYearId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GT86Registry.Core.Entities.Transmission", "Transmission")
                        .WithMany("ModelTransmissions")
                        .HasForeignKey("TransmissionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.ModelYear", b =>
                {
                    b.HasOne("GT86Registry.Core.Entities.Model", "Model")
                        .WithMany("ModelYears")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.Vehicle", b =>
                {
                    b.HasOne("GT86Registry.Core.Entities.Color", "Color")
                        .WithMany("Vehicles")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GT86Registry.Core.Entities.ModelYear", "ModelYear")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelYearId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GT86Registry.Core.Entities.Image", "Image")
                        .WithMany("Vehicles")
                        .HasForeignKey("ProfilePhotoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GT86Registry.Core.Entities.Transmission", "Transmission")
                        .WithMany()
                        .HasForeignKey("TransmissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GT86Registry.Core.Entities.VehicleLocation", "VehicleLocation")
                        .WithMany()
                        .HasForeignKey("VehicleLocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.VehicleLocation", b =>
                {
                    b.HasOne("GT86Registry.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleLocations")
                        .HasForeignKey("VehicleVIN");
                });

            modelBuilder.Entity("GT86Registry.Core.Entities.VehiclesImages", b =>
                {
                    b.HasOne("GT86Registry.Core.Entities.Image", "Image")
                        .WithMany("VehicleImages")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GT86Registry.Core.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleImages")
                        .HasForeignKey("VehicleVIN");
                });
#pragma warning restore 612, 618
        }
    }
}
